version: "3.0"

services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env.example
      - .env

    ports:
      - "8000:8000"

    depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy

    networks:
      - app-network

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bookly
      POSTGRES_PASSWORD: testpass

    ports:
     - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network

    healthcheck:
      test: pg_isready

  redis:
    image: redis:6

    ports:
     - "6379:6379"

    networks:
     - app-network

    healthcheck:
      test: ["CMD", "redis-cli","ping"]

  celery:
    build: .

    command: celery -A src.celery_tasks.c_app worker --loglevel=INFO

    volumes:
      - .:/app

    depends_on:
      - redis

    environment:
      REDIS_URL: ${REDIS_URL}

    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge